## MASTER EXAMPLE CONFIG WITH ALL THE OPTIONS
# The name of your DynMiner executable
DynMiner: "DynMiner.exe"

# This is the wallet to mine to, used for ALL MODES
WalletAddr: "somereceivingaddress"

# Mode should be either: solo, pool, stratum, or SRB
Mode: "solo"

# Miner Options for DynMiner, eg: "GPU,65536,64,0,0" or "CPU,16"
# To multi-gpu mine, just add more values to the array below like this
#MinerOpts: ["GPU,8192,8,0,0","GPU,32768,16,0,1"]
MinerOpts: ["GPU,8192,8,0,0"]

# MinerName is used when pool mining and/or using dmo monitor
# NOTE You can use a minername pulled from an environment variable here.
# To do go, please surround the environment variable you wish to pull the minername from in $ as follows:
# In this example, the environment variable is COMPUTERNAME
# MinerName: $COMPUTERNAME$
MinerName: "MyCoolMiner"

# How often to restart your miner. Use 0 to never restart
RespawnSeconds: 1200

# How often (in minutes) to check for and download updated dmo-wrapminer versions, IF you run it using dmo-launcher
# If this argument is omitted, default is 720 (12 hours)
CheckUpdateFrequency: 360

# DMO Monitor Related Options -- leave blank if not using dmo-monitor
# You can find your cloud key in My Account on dmo-monitor.com
CloudKey: "SOME_CLOUD_KEY"

## SRB Mining Options -- leave blank or ignore if not using SRBMiner
SRBMiner: "SRBMiner-MULTI.exe"
SRBPoolUrl: "pool1.dynamocoin.org:4567"
# SRBMode should either be "CPU" or "GPU"
SRBMode: "CPU"
# Uncomment (remove the # at the beginning of the next line) to add additional options. Example given below for --cpu-threads.
#SRBAdditionalOpts: ["--cpu-threads", "7"]
## END SRB Options


## Foundation Miner Solo Mining Fullnode info, can be ignored or removed for pool/stratum mining
NodeUrl: "http://192.168.1.150:6434"
NodeUser: "username"
NodePass: "password"
## END Solo mining section


## Foundation Miner Pool or Stratum Options, can be ignored or removed for solo mining against a local node
PoolServer: "us-east.deepfields.io"
PoolPort: 4234
StartingDiff: 3
##  END Pool/Stratum section
